default_language_version:
  python: python3.9

default_stages: [commit, push]
files: ''
exclude: '^.txt$'
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: [ "--maxkb=700" ]
      - id: check-docstring-first
      - id: check-json
        exclude: ^.vscode/settings.json
      - id: check-toml
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-ast


  # - repo: local
  #   hooks:
  #     - id: pyupgrade
  #       name: pyupgrade
  #       entry: poetry run pyupgrade --py39-plus
  #       types: [python]
  #       language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        language_version: python3
        exclude: ^tests/
        args:
        - -s
        - B101,B603,B104
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^build/
        args: [--config, setup.cfg]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: ^build/
        args: [--config, setup.cfg]
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.1
    hooks:
      - id: pylint
        exclude: ^build/
        types: [ python ]
        args: ["--rcfile=.pylintrc"]

  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=50]

  - repo: local
    hooks:
      - id: radon-complexity
        name: radon-complexity
        entry: poetry run radon cc --total-average
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: radon-maintainability
        name: radon-maintainability
        entry: poetry run radon mi
        types: [python]
        language: system

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
      - id: add-trailing-comma
